PromptTitle: Aero_MMO Guide
TitleX: 190
DisplayOnLogin: true
Hot_Key: KEY_F12
GUITexture: http://www.almuramc.com/images/playerplus.png
DefaultGuide: Welcome!
GuestGuide: Initial
MemberGuide: Initial
SuperMemberGuide: Initial
ModeratorGuide: Initial
