general:
  Boats_Sink: true
  Movement_Affected: true
  Swimming_Affected: true
  Allow_Physics_Exemptions: true
  Bounce_Causing_Blocks: 1 2 12 35
pistonEntities:
  Pistons_Launch_Entities: true
  Pistons_Launch_Blocks: true
  Piston_Strength: 5.0
  Pushed_Blocks_Launch_Entities: true
armour:
  Leather_Helm: 0
  Leather_Chest: 0
  Leather_Pants: 0
  Leather_Boots: 0
  Iron_Helm: 0
  Iron_Chest: 0
  Iron_Pants: 0
  Iron_Boots: 0
  Gold_Helm: 0
  Gold_Chest: 0
  Gold_Pants: 0
  Gold_Boots: 0
  Diamond_Helm: 0
  Diamond_Chest: 0
  Diamond_Pants: 0
  Diamond_Boots: 0
  Chain_Helm: 0
  Chain_Chest: 0
  Chain_Pants: 0
  Chain_Boots: 0
arrows:
  enabled: true
  head_modifier: 3
  torso_modifier: 2
  legs_modifier: 0.8
  feet_modifier: 0.2
minecarts:
  enabled: true
  death_message: PLAYER never learned to not play on the tracks!
  damage_players: true
  damage_monsters: true
  damage_animals: true
  damage_modifier: 1.0
